### PR TITLE
feat(API): Add TypeScript declaration file

### PR DESCRIPTION
**Pull request by vvo**

### CODE REVIEW

**Comment by Borales** [comment]
@vvo package.json is missing the `types` [entry](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package):

```
  "types": "./lib/index.d.ts"
```

therefore, the Typescript definition file (d.ts) is not being recognized by TypeScript

**Comment by vvo** [comment]
@Borales Thanks, now merged, let me know

**Comment by Borales** [comment]
@vvo it works now

**Comment by Borales** [comment]
@vvo oh, one more thing - the typings are missing the main session methods definitions:

- req.session.set(name, value)
- req.session.get(name)
- req.session.unset(name)
- req.session.destroy()

**Comment by vvo** [comment]
@Borales Sorry I am not using TypeScript so if something is missing, please update it or wait for someone to update it (I have no better answer: I don't know how to fix this :D)

**Pull request merged**
