### PR TITLE
feat(TypeScript): extend withIronSession's `req` type to include `session`

### LINKED ISSUE #298: Typescript: withIronSession does not extend `req` type to include `session`
I may be missing something, but as far as I can tell, `withIronSession` does not extend the `req` type to include `req.session`.

```typescript
export const getServerSideProps: GetServerSideProps<IdentifyProps> = withIronSession(
  async ({ req }: GetServerSidePropsContext) => {
    const { user } = await supabase.auth.api.getUserByCookie(req)
    console.log('session', req.session.get('token'))
...
```

Here, Typescript will complain:

```
Property 'session' does not exist on type 'IncomingMessage & { cookies?: { [key: string]: any; }; }'.ts(2339)
```

I believe an approach similar to `next-connect` to allow passing the req type as a generic to extend the original type might work: https://github.com/hoangvvo/next-connect/blob/efd72ef77878fd0cc0c546c395d3cdbf20ede9fd/lib/index.d.ts#L34

The slightly tricky part is that `withIronSession` is designed to work with both API handlers and `getServerSideProps` so the arguments will be different. I'm not very familiar with adding types to JS, but I'll attempt it. Any hints would be appreciated!

### PR DESCRIPTION
**Pull request by benhickson**
Closes #298 

Hey @vvo! 

I'm pretty new to TypeScript, but loving this library and hoping to help. This code seems to work on my end, but there's probably a better way to to do this?

### CODE REVIEW

**Comment by vvo** [comment]
Hey @benhickson I tried that but got not a big success, can you show how you're using the Handler type in your own code?

Thanks!

**Comment by benhickson** [comment]
Hey, so I can't seem to reproduce the bug that this solved, but this is how i'm typing things in a NextJS API endpoint:

```ts
export default withSession(
  async (req: NextApiRequest & { session: Session }, res: NextApiResponse) => {
    //...
  }
);
```

**Comment by benhickson** [comment]
Actually, I decided to move some of that logic to the `withSession` definition:

```ts
import { NextApiRequest, NextApiResponse } from "next";
import { withIronSession, Session } from "next-iron-session";

export function withSession(
  handler:
    | ((
        req: NextApiRequest & { session: Session },
        res: NextApiResponse,
      ) => any)
    | (({
        req,
        res,
      }: {
        req: NextApiRequest & { session: Session };
        res: NextApiResponse;
      }) => any),
) {
  return withIronSession(handler, {
    password: [
      {
        id: 1,
        password: process.env.SECRET_COOKIE_PASSWORD_01,
      },
    ],
    cookieName: "gift-app-user-cookie",
    cookieOptions: {
      secure: process.env.NODE_ENV === "production",
    },
  });
}
```

Does this look right?

**Comment by Vandivier** [comment]
I think the session type error is what we are trying to solve:
image

**Comment by Vandivier** [comment]
in theory this pr would also close: https://github.com/vvo/next-iron-session/issues/298

however, I see the PR is build-failed for unknown reasons (error log is expired) so I will make a similar change and PR fresh in a minute

**Comment by vvo** [comment]
Hey there @benhickson, thanks a lot for the contribution. It helped the project move to TypeScript in a way, see #356. We'll add additional types moving on. THanks

**Comment by benhickson** [comment]
Thanks @vvo !

**Pull request closed without merging**
